puphpet.extension.jenkins.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionJenkinsBundle:Front:index }

puphpet.extension.jenkins.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionJenkinsBundle:Manifest:index }
