install: 0

settings:
    server_id: ~
    server_token: ~
    agent:
        http_proxy: ~
        https_proxy: ~
        log_file: ~
        log_level: 1
    php:
        agent_timeout: ~
        log_file: ~
        log_level: 1
