puphpet.extension.drush.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionDrushBundle:Front:index }

puphpet.extension.drush.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionDrushBundle:Manifest:index }
