parameters:

services:
    puphpet.extension.drush.configure:
        class: Puphpet\Extension\DrushBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.drush.front_controller:
        class: Puphpet\Extension\DrushBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.drush.manifest_controller:
        class: Puphpet\Extension\DrushBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
