server_ini:
    hhvm.admin_server.password:
    hhvm.admin_server.port:
    hhvm.admin_server.thread_count:
    hhvm.allow_hhas:
    hhvm.allow_scope_binding:
    hhvm.authoritative_mode:
    hhvm.build_type:
    hhvm.check_flush_on_user_close:
    hhvm.check_heap_on_alloc:
    hhvm.check_return_type_hints:
    hhvm.check_sym_link:
    hhvm.code_coverage_output_file:
    hhvm.debug.clear_input_on_success:
    hhvm.debug.core_dump_email:
    hhvm.debug.core_dump_report:
    hhvm.debug.full_backtrace:
    hhvm.debug.local_memcache:
    hhvm.debug.memcache_read_only:
    hhvm.debug.native_stack_trace:
    hhvm.debug.profiler_output_dir:
    hhvm.debug.record_input:
    hhvm.debug.server_error_message:
    hhvm.debug.simple_counter.sample_stack_count:
    hhvm.debug.simple_counter.sample_stack_depth:
    hhvm.debug.stack_trace_timeout:
    hhvm.debug.translate_leak_stack_trace:
    hhvm.debug.translate_source:
    hhvm.debugger.default_sandbox_path:
    hhvm.debugger.disable_ipv6:
    hhvm.debugger.enable_debugger:
    hhvm.debugger.enable_debugger_color:
    hhvm.debugger.enable_debugger_prompt:
    hhvm.debugger.enable_debugger_server:
    hhvm.debugger.enable_debugger_usage_log:
    hhvm.debugger.port:
    hhvm.debugger.rpc.default_auth:
    hhvm.debugger.rpc.default_port:
    hhvm.debugger.rpc.default_timeout:
    hhvm.debugger.rpc.host_domain:
    hhvm.debugger.signal_timeout:
    hhvm.debugger.startup_document:
    hhvm.disable_smart_allocator:
    hhvm.disable_some_repo_auth_notices:
    hhvm.disable_struct_array:
    hhvm.dump_ast:
    hhvm.dump_bytecode:
    hhvm.dump_hhas:
    hhvm.dump_ring_buffer_on_crash:
    hhvm.dump_tc:
    hhvm.dump_tc_anchors:
    hhvm.dynamic_extension_path:
    hhvm.enable_alternative:
    hhvm.enable_args_in_backtraces:
    hhvm.enable_asp_tags:
    hhvm.enable_emit_switch:
    hhvm.enable_emitter_stats:
    hhvm.enable_hip_hop_experimental_syntax:
    hhvm.enable_intrinsics_extension:
    hhvm.enable_numa:
    hhvm.enable_numa_local:
    hhvm.enable_obj_destruct_call:
    hhvm.enable_short_tags:
    hhvm.enable_xhp:
    hhvm.enable_zend_compat:
    hhvm.enable_zend_sorting:
    hhvm.error_handling.assert_active:
    hhvm.error_handling.assert_warning:
    hhvm.error_handling.call_user_handler_on_fatals:
    hhvm.error_handling.enable_hip_hop_errors:
    hhvm.error_handling.log_native_stack_on_oom:
    hhvm.error_handling.max_loop_count:
    hhvm.error_handling.max_serialized_string_size:
    hhvm.error_handling.no_infinite_recursion_detection:
    hhvm.error_handling.notice_frequency:
    hhvm.error_handling.throw_exception_on_bad_method_call:
    hhvm.error_handling.upgrade_level:
    hhvm.error_handling.warn_too_many_arguments:
    hhvm.error_handling.warning_frequency:
    hhvm.force_hh:
    hhvm.gdb_sync_chunks:
    hhvm.hack.lang.ints_overflow_to_ints:
    hhvm.hack.lang.look_for_typechecker:
    hhvm.hack_array_warn_frequency:
    hhvm.hh_prof_server.allocation_profile:
    hhvm.hh_prof_server.enabled:
    hhvm.hh_prof_server.filter.min_alloc_per_req:
    hhvm.hh_prof_server.filter.min_bytes_per_req:
    hhvm.hh_prof_server.port:
    hhvm.hh_prof_server.profile_client_mode:
    hhvm.hh_prof_server.threads:
    hhvm.hh_prof_server.timeout_seconds:
    hhvm.hhbc_arena_chunk_size:
    hhvm.hhir_alloc_simd_regs:
    hhvm.hhir_bytecode_control_flow:
    hhvm.hhir_cse:
    hhvm.hhir_dead_code_elim:
    hhvm.hhir_direct_exit:
    hhvm.hhir_enable_coalescing:
    hhvm.hhir_enable_gen_time_inlining:
    hhvm.hhir_enable_pre_coloring:
    hhvm.hhir_extra_opt_pass:
    hhvm.hhir_gen_opts:
    hhvm.hhir_generate_asserts:
    hhvm.hhir_global_value_numbering:
    hhvm.hhir_inline_frame_opts:
    hhvm.hhir_inline_singletons:
    hhvm.hhir_inlining_max_cost:
    hhvm.hhir_inlining_max_depth:
    hhvm.hhir_inlining_max_return_dec_refs:
    hhvm.hhir_memory_opts:
    hhvm.hhir_num_free_regs:
    hhvm.hhir_prediction_opts:
    hhvm.hhir_refcount_opts:
    hhvm.hhir_refcount_opts_always_sink:
    hhvm.hhir_relax_guards:
    hhvm.hhir_simplification:
    hhvm.hhir_stress_codegen_blocks:
    hhvm.hhir_validate_ref_count:
    hhvm.hot_func_count:
    hhvm.http.default_timeout:
    hhvm.http.slow_query_threshold:
    hhvm.initial_named_entity_table_size:
    hhvm.initial_static_string_table_size:
    hhvm.jit:
    hhvm.jit_a_cold_size:
    hhvm.jit_a_frozen_size:
    hhvm.jit_a_hot_size:
    hhvm.jit_a_max_usage:
    hhvm.jit_a_prof_size:
    hhvm.jit_a_size:
    hhvm.jit_always_interp_one:
    hhvm.jit_cpu:
    hhvm.jit_disabled_by_hphpd:
    hhvm.jit_enable_rename_function:
    hhvm.jit_global_data_size:
    hhvm.jit_global_translation_limit:
    hhvm.jit_keep_dbg_files:
    hhvm.jit_llvm:
    hhvm.jit_llvm_basic_opt:
    hhvm.jit_llvm_cond_tail:
    hhvm.jit_llvm_counters:
    hhvm.jit_llvm_discard:
    hhvm.jit_llvm_fast_i_sel:
    hhvm.jit_llvm_opt_level:
    hhvm.jit_llvm_opt_size:
    hhvm.jit_llvm_size_level:
    hhvm.jit_loops:
    hhvm.jit_max_region_instrs:
    hhvm.jit_max_translations:
    hhvm.jit_no_gdb:
    hhvm.jit_pgo:
    hhvm.jit_pgo_array_get_stress:
    hhvm.jit_pgo_hot_only:
    hhvm.jit_pgo_region_selector:
    hhvm.jit_pgo_release_vv_min_percent:
    hhvm.jit_pgo_string_spec:
    hhvm.jit_pgo_threshold:
    hhvm.jit_pgo_use_post_conditions:
    hhvm.jit_profile_interp_requests:
    hhvm.jit_profile_record:
    hhvm.jit_profile_requests:
    hhvm.jit_profile_warmup_requests:
    hhvm.jit_pseudomain:
    hhvm.jit_region_selector:
    hhvm.jit_relocation_size:
    hhvm.jit_require_write_lease:
    hhvm.jit_stress_lease:
    hhvm.jit_target_cache_size:
    hhvm.jit_timer:
    hhvm.jit_trans_counters:
    hhvm.jit_unlikely_dec_ref_percent:
    hhvm.jit_use_vtune_api:
    hhvm.keep_perf_pid_map:
    hhvm.log.access_log_default_format:
    hhvm.log.admin_log.file:
    hhvm.log.admin_log.format:
    hhvm.log.admin_log.sym_link:
    hhvm.log.always_escape_log:
    hhvm.log.always_log_unhandled_exceptions:
    hhvm.log.drop_cache_chunk_size:
    hhvm.log.file:
    hhvm.log.force_error_reporting_level:
    hhvm.log.header:
    hhvm.log.header_mangle:
    hhvm.log.level:
    hhvm.log.max_messages_per_request:
    hhvm.log.native_stack_trace:
    hhvm.log.no_silencer:
    hhvm.log.runtime_error_reporting_level:
    hhvm.log.sym_link:
    hhvm.log.use_cronolog:
    hhvm.log.use_log_file:
    hhvm.log.use_request_log:
    hhvm.log.use_syslog:
    hhvm.mail.force_extra_parameters:
    hhvm.mail.sendmail_path:
    hhvm.map_hot_text_huge:
    hhvm.map_tc_huge:
    hhvm.map_tgt_cache_huge:
    hhvm.max_cpu_time:
    hhvm.max_low_mem_huge_pages:
    hhvm.max_wall_time:
    hhvm.mysql.connect_timeout:
    hhvm.mysql.kill_on_timeout:
    hhvm.mysql.max_retry_open_on_fail:
    hhvm.mysql.max_retry_query_on_fail:
    hhvm.mysql.read_only:
    hhvm.mysql.read_timeout:
    hhvm.mysql.slow_query_threshold:
    hhvm.mysql.socket:
    hhvm.mysql.typed_results:
    hhvm.mysql.wait_timeout:
    hhvm.num_single_jit_requests:
    hhvm.pagelet_server.queue_limit:
    hhvm.pagelet_server.thread_count:
    hhvm.pagelet_server.thread_drop_cache_timeout_seconds:
    hhvm.pagelet_server.thread_drop_stack:
    hhvm.pagelet_server.thread_round_robin:
    hhvm.pcre.jit:
    hhvm.pcre_cache_type:
    hhvm.pcre_expire_interval:
    hhvm.pcre_table_size:
    hhvm.perf_data_map:
    hhvm.perf_pid_map:
    hhvm.pid_file:
    hhvm.preg.backtrace_limit:
    hhvm.preg.error_log:
    hhvm.preg.recursion_limit:
    hhvm.profile_bc:
    hhvm.profile_heap_across_requests:
    hhvm.profile_hw_enable:
    hhvm.profile_hw_events:
    hhvm.proxy.origin:
    hhvm.proxy.percentage:
    hhvm.proxy.proxy_urls:
    hhvm.proxy.retry:
    hhvm.proxy.serve_urls:
    hhvm.random_hot_funcs:
    hhvm.record_code_coverage:
    hhvm.repo.authoritative:
    hhvm.repo.central.path:
    hhvm.repo.commit:
    hhvm.repo.debug_info:
    hhvm.repo.journal:
    hhvm.repo.local.mode:
    hhvm.repo.local.path:
    hhvm.repo.mode:
    hhvm.repo.preload:
    hhvm.resource_limit.core_file_size:
    hhvm.resource_limit.core_file_size_override:
    hhvm.resource_limit.drop_cache_cycle:
    hhvm.resource_limit.heap_high_water_mark:
    hhvm.resource_limit.heap_low_water_mark:
    hhvm.resource_limit.heap_reset_count_base:
    hhvm.resource_limit.heap_reset_count_multiple:
    hhvm.resource_limit.heap_size_mb:
    hhvm.resource_limit.max_memcache_key_count:
    hhvm.resource_limit.max_rss:
    hhvm.resource_limit.max_rss_polling_cycle:
    hhvm.resource_limit.max_socket:
    hhvm.resource_limit.max_sql_row_count:
    hhvm.resource_limit.rss:
    hhvm.resource_limit.serialization_size_limit:
    hhvm.resource_limit.socket_default_timeout:
    hhvm.resource_limit.string_offset_limit:
    hhvm.sandbox.conf_file:
    hhvm.sandbox.directories_root:
    hhvm.sandbox.fallback:
    hhvm.sandbox.from_common_root:
    hhvm.sandbox.home:
    hhvm.sandbox.logs_root:
    hhvm.sandbox.sandbox_mode:
    hhvm.server.allow_duplicate_cookies:
    hhvm.server.always_populate_raw_post_data:
    hhvm.server.always_use_relative_path:
    hhvm.server.apc.allow_object:
    hhvm.server.apc.enable_apc:
    hhvm.server.apc.enable_apc_serialize:
    hhvm.server.apc.enable_const_load:
    hhvm.server.apc.expire_on_sets:
    hhvm.server.apc.file_storage.advise_out_period:
    hhvm.server.apc.file_storage.enable:
    hhvm.server.apc.file_storage.flag_key:
    hhvm.server.apc.file_storage.keep_file_linked:
    hhvm.server.apc.file_storage.prefix:
    hhvm.server.apc.force_const_load_to_apc:
    hhvm.server.apc.key_frequency_update_period:
    hhvm.server.apc.key_maturity_threshold:
    hhvm.server.apc.load_thread:
    hhvm.server.apc.maximum_capacity:
    hhvm.server.apc.mem_model_treadmill:
    hhvm.server.apc.prime_library:
    hhvm.server.apc.purge_frequency:
    hhvm.server.apc.purge_rate:
    hhvm.server.apc.ttl_limit:
    hhvm.server.backlog:
    hhvm.server.connection_limit:
    hhvm.server.connection_timeout_seconds:
    hhvm.server.dangling_wait:
    hhvm.server.default_charset_name:
    hhvm.server.default_document:
    hhvm.server.default_server_name_suffix:
    hhvm.server.enable_cuf_async:
    hhvm.server.enable_early_flush:
    hhvm.server.enable_keep_alive:
    hhvm.server.enable_on_demand_uncompress:
    hhvm.server.enable_output_buffering:
    hhvm.server.enable_ssl:
    hhvm.server.enable_static_content_from_disk:
    hhvm.server.enable_static_content_m_map:
    hhvm.server.error_document404:
    hhvm.server.error_document500:
    hhvm.server.evil_shutdown:
    hhvm.server.exit_on_bind_fail:
    hhvm.server.expires_active:
    hhvm.server.expires_default:
    hhvm.server.expose_hphp:
    hhvm.server.expose_xfb_debug:
    hhvm.server.expose_xfb_server:
    hhvm.server.fatal_error_message:
    hhvm.server.file_cache:
    hhvm.server.file_socket:
    hhvm.server.fix_path_info:
    hhvm.server.forbidden_as404:
    hhvm.server.force_chunked_encoding:
    hhvm.server.force_compression.cookie:
    hhvm.server.force_compression.param:
    hhvm.server.force_compression.url:
    hhvm.server.force_server_name_to_header:
    hhvm.server.graceful_shutdown_wait:
    hhvm.server.gzip_compression_level:
    hhvm.server.gzip_max_compression_level:
    hhvm.server.harsh_shutdown:
    hhvm.server.host:
    hhvm.server.http_safe_mode:
    hhvm.server.image_memory_max_bytes:
    hhvm.server.implicit_flush:
    hhvm.server.ip:
    hhvm.server.kill_on_sigterm:
    hhvm.server.lib_event_sync_send:
    hhvm.server.light_process_count:
    hhvm.server.light_process_file_prefix:
    hhvm.server.lock_code_memory:
    hhvm.server.max_array_chain:
    hhvm.server.max_post_size:
    hhvm.server.max_request_age_factor:
    hhvm.server.memory_head_room:
    hhvm.server.output_handler:
    hhvm.server.path_debug:
    hhvm.server.port:
    hhvm.server.psp_cpu_timeout_seconds:
    hhvm.server.psp_timeout_seconds:
    hhvm.server.request_body_read_limit:
    hhvm.server.request_init_document:
    hhvm.server.request_init_function:
    hhvm.server.request_memory_max_bytes:
    hhvm.server.request_timeout_seconds:
    hhvm.server.response_queue_count:
    hhvm.server.safe_file_access:
    hhvm.server.shutdown_listen_no_work:
    hhvm.server.shutdown_listen_wait:
    hhvm.server.ssl_certificate_dir:
    hhvm.server.ssl_certificate_file:
    hhvm.server.ssl_certificate_key_file:
    hhvm.server.ssl_port:
    hhvm.server.startup_document:
    hhvm.server.stat_cache:
    hhvm.server.takeover_filename:
    hhvm.server.thread_count:
    hhvm.server.thread_drop_cache_timeout_seconds:
    hhvm.server.thread_drop_stack:
    hhvm.server.thread_job_lifo_switch_threshold:
    hhvm.server.thread_job_max_queuing_milli_seconds:
    hhvm.server.thread_round_robin:
    hhvm.server.tls_client_cipher_spec:
    hhvm.server.tls_disable_tls1_2:
    hhvm.server.type:
    hhvm.server.unserialization_whitelist_check:
    hhvm.server.unserialization_whitelist_check_warning_only:
    hhvm.server.upload.enable_file_uploads:
    hhvm.server.upload.enable_upload_progress:
    hhvm.server.upload.rfc1867freq:
    hhvm.server.upload.rfc1867name:
    hhvm.server.upload.rfc1867prefix:
    hhvm.server.upload.upload_max_file_size:
    hhvm.server.upload.upload_tmp_dir:
    hhvm.server.use_direct_copy:
    hhvm.server.user:
    hhvm.server.utf8ize_replace:
    hhvm.server.warmup_document:
    hhvm.server.warmup_throttle_request_count:
    hhvm.server.warn_on_collection_to_array:
    hhvm.server.whitelist_exec:
    hhvm.server.whitelist_exec_warning_only:
    hhvm.server.xfb_debug_ssl_key:
    hhvm.simple_xml.empty_namespace_matches_all:
    hhvm.simulate_arm:
    hhvm.soft_closure_return_type_hints:
    hhvm.spin_on_crash:
    hhvm.stats.apc:
    hhvm.stats.enable:
    hhvm.stats.enable_hot_profiler:
    hhvm.stats.max_slot:
    hhvm.stats.memcache:
    hhvm.stats.memcache_key:
    hhvm.stats.memory:
    hhvm.stats.network_io:
    hhvm.stats.profiler_max_trace_buffer:
    hhvm.stats.profiler_trace_buffer:
    hhvm.stats.profiler_trace_expansion:
    hhvm.stats.slot_duration:
    hhvm.stats.sql:
    hhvm.stats.sql_table:
    hhvm.stats.web:
    hhvm.stats.xsl:
    hhvm.stats.xsl_proxy:
    hhvm.tc_num_huge_cold_mb:
    hhvm.tc_num_huge_hot_mb:
    hhvm.timeouts_use_wall_time:
    hhvm.vm_initial_global_table_size:
    hhvm.vm_stack_elms:
    hhvm.xbox.default_local_timeout_milli_seconds:
    hhvm.xbox.default_remote_timeout_seconds:
    hhvm.xbox.process_message_func:
    hhvm.xbox.server_info.always_reset:
    hhvm.xbox.server_info.log_info:
    hhvm.xbox.server_info.max_duration:
    hhvm.xbox.server_info.max_queue_length:
    hhvm.xbox.server_info.max_request:
    hhvm.xbox.server_info.port:
    hhvm.xbox.server_info.request_init_document:
    hhvm.xbox.server_info.request_init_function:
    hhvm.xbox.server_info.thread_count:
    hhvm.xbox.server_info.warmup_document:
    hhvm.xenon.force_always_on:
    hhvm.xenon.period:

php_ini:
    allow_url_fopen:
    apc.enable_cli:
    apc.enabled:
    apc.stat:
    doc_root:
    expose_php:
    extension_dir:
    file_uploads:
    arg_separator.input:
    arg_separator.output:
    bcmath.scale:
    date.default_latitude:
    date.default_longitude:
    date.sunrise_zenith:
    date.sunset_zenith:
    date.timezone:
    default_charset:
    default_mimetype:
    default_socket_timeout:
    display_errors:
    error_log:
    error_reporting:
    highlight.comment:
    highlight.default:
    highlight.html:
    highlight.keyword:
    highlight.string:
    imagick.locale_fix:
    imagick.progress_monitor:
    include_path:
    intl.default_locale:
    log_errors:
    max_execution_time:
    maximum_execution_time:
    memcache.hash_function:
    memcache.hash_strategy:
    memcached.sess_prefix:
    memory_limit:
    mysqli.default_host:
    mysqli.default_port:
    mysqli.default_pw:
    mysqli.default_socket:
    mysqli.default_user:
    open_basedir:
    pcre.backtrack_limit:
    pcre.recursion_limit:
    request_order:
    session.auto_start:
    session.cache_expire:
    session.cache_limiter:
    session.cookie_domain:
    session.cookie_httponly:
    session.cookie_lifetime:
    session.cookie_path:
    session.cookie_secure:
    session.entropy_file:
    session.entropy_length:
    session.gc_divisor:
    session.gc_maxlifetime:
    session.gc_probability:
    session.hash_bits_per_character:
    session.hash_function:
    session.name:
    session.referer_check:
    session.save_handler:
    session.save_path:
    session.serialize_handler:
    session.use_cookies:
    session.use_only_cookies:
    session.use_trans_sid:
    track_errors:
    user_agent:
    variables_order:
    zlib.output_compression:
    zlib.output_compression_level:
