puphpet.nginx.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:Nginx:index }

puphpet.nginx.upstream:
    pattern:  /upstream
    defaults: { _controller: PuphpetMainBundle:Nginx:upstream }

puphpet.nginx.proxy:
    pattern:  /proxy
    defaults: { _controller: PuphpetMainBundle:Nginx:proxy }

puphpet.nginx.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetMainBundle:Nginx:vhost }

puphpet.nginx.location:
    pattern:  /location/{vhostId}
    defaults: { _controller: PuphpetMainBundle:Nginx:location }
