parameters:

services:
    puphpet.extension.vagrantfile.rackspace.configure:
        class: Puphpet\Extension\VagrantfileRackspaceBundle\Configure
        arguments:
            - "@service_container"
        tags:
            - { name: puphpet.extension, group: "vagrantfile", priority: 350 }

    puphpet.extension.vagrantfile.rackspace.front_controller:
        class: Puphpet\Extension\VagrantfileRackspaceBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.rackspace.manifest_controller:
        class: Puphpet\Extension\VagrantfileRackspaceBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
