sudo: false
language: ruby
bundler_args: --no-deployment

script:
  - bundle exec rake validate
  - bundle exec rake lint
  - bundle exec rake spec

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.7.5" DEPLOY="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0"

before_deploy:
  - bundle exec puppet module build

deploy:
  provider: releases
  api-key:
      secure: "cMMxLnCo0XJBJ+e8BCI6EfO+32xAJnjxVPQTtnT62xg85+ESTqCwfrB/nHVFQYfNBvw6BVVi26jpa/PXHC3aL9RlJKZSoLg9TVbQFDOwBHdqpyYcAKUg90pC4WQrnvONO1AaBjFuNosGKHagCBW+mD696T6SsjNsFfW4xgE2JXM="
  file: "$(ls $TRAVIS_BUILD_DIR/pkg/s12v-blackfire-*.tar.gz | head -n 1)"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $DEPLOY = yes
