name          'petems-swap_file'
version '0.1.3'
source        'git://github.com/petems/puppet-swap_file.git'
author        'petems'
license       'Apache License, Version 2.0'
summary       'Swap file management with Puppet'
description   'Create swap files for Linux systems with Puppet'
project_page  'https://github.com/petems/puppet-swap_file'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
