puphpet.extension.wpcli.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionWPCliBundle:Front:index }

puphpet.extension.wpcli.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionWPCliBundle:Manifest:index }
