forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apache',
    :git => 'https://github.com/puppetlabs/puppetlabs-apache.git',
    :ref => '7dde9fc31e'
mod 'puppetlabs/apt',
    :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
    :ref => '1.8.0'
mod 'keen99/beanstalkd',
    :git => 'https://github.com/keen99/puppet-beanstalkd.git',
    :ref => '1.0.1'
mod 's12v/blackfire',
    :git => 'https://github.com/puphpet/puppet-blackfire.git',
    :ref => 'af4eae8'
mod 'tPl0ch/composer',
    :git => 'https://github.com/puphpet/puppet-composer.git',
    :ref => 'c4f9478'
mod 'puppetlabs/concat',
    :git => 'https://github.com/puppetlabs/puppetlabs-concat.git',
    :ref => '1.1.1'
mod 'elasticsearch/elasticsearch',
    :git => 'https://github.com/puphpet/puppet-elasticsearch.git',
    :ref => '0.9.9'
mod 'garethr/erlang',
    :git => 'https://github.com/garethr/garethr-erlang.git',
    :ref => '91d8ec73c3'
mod 'puppetlabs/firewall',
    :git => 'https://github.com/puppetlabs/puppetlabs-firewall.git',
    :ref => '1.1.1'
mod 'n1tr0g/gnupg',
    :git => 'https://github.com/n1tr0g/golja-gnupg.git',
    :ref => '1.2.1'
mod 'puppetlabs/inifile',
    :git => 'https://github.com/puppetlabs/puppetlabs-inifile.git',
    :ref => '1.2.0'
mod 'puppetlabs/java',
    :git => 'https://github.com/puppetlabs/puppetlabs-java.git',
    :ref => '1.3.0'
mod 'attachmentgenie/locales',
    :git => 'https://github.com/saz/puppet-locales.git',
    :ref => 'v2.2.2'
mod 'puppetlabs/mongodb',
    :git => 'https://github.com/puppetlabs/puppetlabs-mongodb.git',
    :ref => '38ceb81e36'
mod 'puppetlabs/mysql',
    :git => 'https://github.com/puppetlabs/puppetlabs-mysql.git',
    :ref => '3.3.0'
mod 'jfryman/nginx',
    :git => 'https://github.com/puphpet/puppet-nginx.git',
    :ref => 'ea75350'
mod 'puppetlabs/ntp',
    :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git',
    :ref => '4.1.1'
mod 'puphpet/php',
    :git => 'https://github.com/puphpet/puppet-php.git',
    :ref => 'c5aa4bf'
mod 'puppetlabs/postgresql',
    :git => 'https://github.com/puppetlabs/puppetlabs-postgresql.git',
    :ref => '4.6.0'
mod 'puphpet/puphpet',
    :git => 'https://github.com/puphpet/puppet-puphpet.git',
    :ref => '08a00e2'
mod 'example42/puppi',
    :git => 'https://github.com/puphpet/puppi.git',
    :ref => '5dd5091'
mod 'daenney/pyenv',
    :git => 'https://github.com/puphpet/puppet-pyenv.git',
    :ref => '062ae72'
mod 'puppetlabs/rabbitmq',
    :git => 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git',
    :ref => '5.2.0'
mod 'puphpet/redis',
    :git => 'https://github.com/puphpet/puppet-redis.git',
    :ref => '233cc8f'
mod 'maestrodev/rvm'
mod 'example42/solr',
    :git => 'https://github.com/puphpet/puppet-solr.git',
    :ref => 'a5ce62c'
mod 'petems/swap_file',
    :git => 'https://github.com/petems/puppet-swap_file.git',
    :ref => '39582afda5'
mod 'ajcrowe/supervisord',
    :git => 'https://github.com/puphpet/puppet-supervisord.git',
    :ref => '17643f1'
mod 'puppetlabs/stdlib',
    :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
    :ref => '4dab70b305'
mod 'puppetlabs/vcsrepo',
    :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git',
    :ref => '0.2.0'
mod 'example42/yum',
    :git => 'https://github.com/example42/puppet-yum.git',
    :ref => 'v2.1.25'
