target: ~

vm:
    box: digital_ocean
    hostname: master
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        digital_ocean:
            image: ~
            region: ~
            size: ~
            token: ~
            ssh_key_name: Vagrant
    provision:
        puppet:
            manifests_path: "puphpet/puppet"
            manifest_file: "site.pp"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
                - "--parser future"
    synced_folder: []

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: ~
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: detect
