puphpet.vagrantfile_digitalocean.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileDigitalOcean:index }

puphpet.vagrantfile_digitalocean.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileDigitalOcean:syncedFolder }
