parameters:

services:
    puphpet.extension.nginx.configure:
        class: Puphpet\Extension\NginxBundle\Configure
        arguments:
            - "@service_container"
        tags:
            - { name: puphpet.extension, group: "webserver", priority: 270 }

    puphpet.extension.nginx.front_controller:
        class: Puphpet\Extension\NginxBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.nginx.manifest_controller:
        class: Puphpet\Extension\NginxBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
