puphpet.mariadb.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:MariaDb:index }

puphpet.mariadb.add_user:
    pattern:  /add-user
    defaults: { _controller: PuphpetMainBundle:MariaDb:addUser }

puphpet.mariadb.add_database:
    pattern:  /add-database
    defaults: { _controller: PuphpetMainBundle:MariaDb:addDatabase }

puphpet.mariadb.add_grant:
    pattern:  /add-grant
    defaults: { _controller: PuphpetMainBundle:MariaDb:addGrant }
