name 'example42-solr'
version '2.0.6'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-solr'
summary 'Puppet module for solr'
description 'This module installs and manages solr. Check README for details.'
dependency 'puppetlabs/stdlib', '>=2.0.0'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
