puphpet.vagrantfile_aws.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileAws:index }

puphpet.vagrantfile_aws.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileAws:syncedFolder }
