puphpet.extension.apc.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionApcBundle:Front:index }

puphpet.extension.apc.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionApcBundle:Manifest:index }
