config.php_modules:
  - php5-adodb
  - php5-auth-pam
  - php5-cgi
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dbg
  - php5-enchant
  - php5-exactimage
  - php5-ffmpeg
  - php5-fpm
  - php5-gd
  - php5-geoip
  - php5-gmp
  - php5-imagick
  - php5-imap
  - php5-interbase
  - php5-intl
  - php5-lasso
  - php5-ldap
  - php5-librdf
  - php5-mapscript
  - php5-mcrypt
  - php5-memcache
  - php5-memcached
  - php5-midgard2
  - php5-ming
  - php5-mysql
  - php5-mysqlnd
  - php5-odbc
  - php5-pgsql
  - php5-ps
  - php5-pspell
  - php5-radius
  - php5-readline
  - php5-recode
  - php5-remctl
  - php5-rrd
  - php5-sasl
  - php5-snmp
  - php5-sqlite
  - php5-suhosin
  - php5-svn
  - php5-sybase
  - php5-tidy
  - php5-tokyo-tyrant
  - php5-uuid
  - php5-xcache
  - php5-xmlrpc
  - php5-xsl
  - php-apc
  - php-auth
  - php-auth-http
  - php-auth-sasl
  - phpbb3
  - phpbb3-l10n
  - php-benchmark
  - php-cache
  - php-cache-lite
  - php-codesniffer
  - php-compat
  - php-config
  - php-console-table
  - php-crypt-blowfish
  - php-crypt-cbc
  - php-crypt-gpg
  - php-date
  - php-db
  - php-doc
  - php-elisp
  - php-event-dispatcher
  - php-file
  - php-fpdf
  - phpgacl
  - php-geshi
  - php-getid3
  - php-gettext
  - php-html-common
  - php-htmlpurifier
  - php-html-safe
  - php-html-template-it
  - php-http
  - php-http-request
  - php-http-upload
  - php-http-webdav-server
  - php-image-text
  - php-imlib
  - php-kolab-filter
  - php-kolab-freebusy
  - phpldapadmin
  - php-letodms-core
  - php-letodms-lucene
  - php-log
  - php-mail
  - php-mail-mime
  - php-mail-mimedecode
  - php-mdb2
  - php-mdb2-driver-mysql
  - php-mdb2-driver-pgsql
  - php-mdb2-driver-sqlite
  - php-mime-type
  - phpmyadmin
  - php-mythtv
  - php-net-checkip
  - php-net-dime
  - php-net-dnsbl
  - php-net-ftp
  - php-net-imap
  - php-net-ipv4
  - php-net-ipv6
  - php-net-ldap
  - php-net-ldap2
  - php-net-lmtp
  - php-net-nntp
  - php-net-ping
  - php-net-portscan
  - php-net-sieve
  - php-net-smartirc
  - php-net-smtp
  - php-net-socket
  - php-net-url
  - php-net-whois
  - php-numbers-words
  - php-openid
  - php-pager
  - phppgadmin
  - php-radius-legacy
  - phpreports
  - php-services-json
  - php-services-weather
  - php-soap
  - phpsysinfo
  - php-text-captcha
  - php-text-figlet
  - php-text-password
  - php-text-wiki
  - phpwebcounter
  - phpwebcounter-extra
  - php-wikidiff2
  - php-xajax
  - php-xml-htmlsax3
  - php-xml-parser
  - php-xml-rpc
  - php-xml-rpc2
  - php-xml-rss
  - php-xml-serializer
  - php-zeroc-ice
