empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
    -
        image: centos-6-v20131120
        long_name: CentOS 6 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: debian-7-wheezy-v20131120
        long_name: Debian Wheezy 7 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: backports-debian-7-wheezy-v20131127
        long_name: Debian Wheezy 7 x64 Backports
        php_versions:
            - 5.5
            - 5.4

available_sizes:
    f1-micro: "f1-micro: 1 vCPU / 0.6 GB Memory"
    g1-small: "g1-small: 1 vCPU / 1.7 GB Memory"
    n1-highcpu-2: "n1-highcpu-2: 2 vCPUs / 1.8 GB Memory"
    n1-highcpu-4: "n1-highcpu-4: 4 vCPUs / 3.6 GB Memory"
    n1-highcpu-8: "n1-highcpu-8: 8 vCPUs / 7.2 GB Memory"
    n1-highmem-2: "n1-highmem-2: 2 vCPUs / 13 GB Memory"
    n1-highmem-4: "n1-highmem-4: 4 vCPUs / 26 GB Memory"
    n1-highmem-8: "n1-highmem-8: 8 vCPUs / 52 GB Memory"
    n1-standard-1: "n1-standard-1: 1 vCPU / 3.8 GB Memory"
    n1-standard-2: "n1-standard-2: 2 vCPUs / 7.5 GB Memory"
    n1-standard-4: "n1-standard-4: 4 vCPUs / 15 GB Memory"
    n1-standard-8: "n1-standard-8: 8 vCPUs / 30 GB Memory"

available_regions:
    - europe-west1-a
    - europe-west-1b
    - us-central1-a
    - us-central1-b
