parameters:

services:
    puphpet.extension.vagrantfile.gce.configure:
        class: Puphpet\Extension\VagrantfileGceBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.vagrantfile.gce.front_controller:
        class: Puphpet\Extension\VagrantfileGceBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.gce.manifest_controller:
        class: Puphpet\Extension\VagrantfileGceBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
