puphpet.extension.varnish.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionVarnishBundle:Front:index }

puphpet.extension.varnish.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionVarnishBundle:Manifest:index }
