parameters:

services:
    puphpet.extension.varnish.configure:
        class: Puphpet\Extension\VarnishBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.varnish.front_controller:
        class: Puphpet\Extension\VarnishBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.varnish.manifest_controller:
        class: Puphpet\Extension\VarnishBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
