puphpet.vagrantfile_rackspace.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileRackspace:index }

puphpet.vagrantfile_rackspace.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileRackspace:syncedFolder }
