providers:
    -
        name: virtualbox
        long_name: VirtualBox
        description: >
            Free! Not as performant as VMWare. Free!
            <a href="https://www.virtualbox.org/wiki/Downloads" target="_blank">Download Virtualbox here</a>.
        os_support: Windows, OS X &amp; Linux
        performance: 1
        default_ip: 192.168.56.101
    -
        name: vmware_fusion
        long_name: VMWare Fusion
        description: >
            More performant than VirtualBox.
            <a href="http://send.onenetworkdirect.net/z/33484/CD207605/" target="_blank">Requires purchase of VMWare Fusion</a>
            (affiliate link - help support this free service)
            and purchase of <a href="http://www.vagrantup.com/vmware" target="_blank">Vagrant VMWare Fusion Plugin</a>.
        os_support: OS X only
        performance: 3
        default_ip: 192.168.57.101
    -
        name: vmware_workstation
        long_name: VMWare Workstation
        description: >
            More performant than VirtualBox.
            <a href="http://send.onenetworkdirect.net/z/33485/CD207605/" target="_blank">Requires purchase of VMWare Workstation</a>
            (affiliate link - help support this free service)
            and purchase of <a href="http://www.vagrantup.com/vmware" target="_blank">Vagrant VMWare Workstation Plugin</a>.
        os_support: Windows &amp; Linux
        performance: 3
        default_ip: 192.168.57.101
    -
        name: parallels
        long_name: Parallels Desktop
        description: >
            More performant than VirtualBox.
            <a href="http://www.tkqlhce.com/click-7569625-11516363" target="_blank">Requires purchase of Parallels Desktop 9</a>
            (affiliate link - help support this free service)
            and installing the free <a href="https://github.com/Parallels/vagrant-parallels" target="_blank">Vagrant Parallels Plugin</a>.
        os_support: OS X only
        performance: 3
        default_ip: 192.168.58.101

boxes:
    -
        url: puphpet/centos65-x64
        os: centos
        short_name: puphpet/centos65-x64
        long_name: CentOS 6 x64
        php_versions:
            - 5.6
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/debian75-x64
        os: debian
        short_name: puphpet/debian75-x64
        long_name: Debian Wheezy 7 x64
        php_versions:
            - 5.6
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/ubuntu1404-x64
        os: ubuntu
        short_name: puphpet/ubuntu1404-x64
        long_name: Ubuntu Trusty 14.04 LTS x64
        php_versions:
            - 7.0
            - 5.6
            - 5.5
            - HHVM
    -
        url: puphpet/ubuntu1404-x32
        os: ubuntu
        short_name: puphpet/ubuntu1404-x32
        long_name: Ubuntu Trusty 14.04 LTS x32
        php_versions:
            - 5.6
            - 5.5
            - HHVM
    -
        url: puphpet/ubuntu1204-x64
        os: ubuntu
        short_name: puphpet/ubuntu1204-x64
        long_name: Ubuntu Precise 12.04 LTS x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM

empty_synced_folder:
    source: ~
    target: ~
    id: vagrant-root
    sync_type: default
    owner: 'www-data'
    group: 'www-data'
    rsync:
        args:
            - '--verbose'
            - '--archive'
            - '-z'
        exclude:
            - '.vagrant/'
            - '.git/'
        auto: true

empty_forwarded_port:
    host: ~
    guest: ~
