puphpet.extension.solr.homepage:
    pattern:  /
    defaults: { _controller: PuphpetExtensionSolrBundle:Front:index }

puphpet.extension.solr.manifest:
    pattern:  /manifest
    defaults: { _controller: PuphpetExtensionSolrBundle:Manifest:index }
