parameters:

services:
    puphpet.extension.solr.configure:
        class: Puphpet\Extension\SolrBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.solr.front_controller:
        class: Puphpet\Extension\SolrBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.solr.manifest_controller:
        class: Puphpet\Extension\SolrBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
