versions:
    - 7.0.0-alpha3
    - 7.0.0-alpha2
    - 7.0.0-alpha1
    - 6.3.0
    - 6.2.0
    - 6.1.0
    - 6.0.0
    - 5.11.0
    - 5.10.0
    - 5.9.0
    - 5.8.0
    - 5.7.0
    - 5.6.0
    - 5.5.0
    - 5.4.0
    - 5.3.0
    - 5.2.0
    - 5.1.0
    - 5.0.0
    - 4.6.0
    - 4.5.0
    - 4.4.0
    - 4.3.0
    - 4.2.0
    - 4.1.0
    - 4.0.0
    - 3.3.0
    - 3.2.0
    - 3.1.0
    - 3.0.0
    - 2.1.0
    - 2.0.0
