parameters:

services:
    puphpet.extension.apache.configure:
        class: Puphpet\Extension\ApacheBundle\Configure
        arguments:
            - "@service_container"
        tags:
            - { name: puphpet.extension, group: "webserver", priority: 290 }

    puphpet.extension.apache.front_controller:
        class: Puphpet\Extension\ApacheBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.apache.manifest_controller:
        class: Puphpet\Extension\ApacheBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
