puphpet.apache.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:Apache:index }

puphpet.apache.vhost:
    pattern:  /vhost
    defaults: { _controller: PuphpetMainBundle:Apache:vhost }

puphpet.apache.directory:
    pattern:  /directory
    defaults: { _controller: PuphpetMainBundle:Apache:directory }

puphpet.apache.files_match:
    pattern:  /files-match
    defaults: { _controller: PuphpetMainBundle:Apache:filesMatch }
